### PR TITLE
Support for titleless popups and missing "CommonAdminTools" Folder.

### PR DESCRIPTION
**Pull request by Hattshire**
Some little modifications to deal with this issue: https://github.com/alur/nModules/issues/50

### CODE REVIEW

**Comment by Hattshire** [comment]
I didn't noticed the rewrite 😖

**Comment by alur** [comment]
Don't worry too much about the rewrite. It's an idea I had for making the modules more independent of eachother, but unfortunately I just don't have the time to work on it these days.

Thanks for the PR :)

**Comment by Sulfurtank** [comment]
how to disable titles?

**Comment by AnrDaemon** [comment]
@Sulfurtank , if you have a generic question, [ask it on the forums](http://forums.litestep.info/), please.

**Pull request merged**
